/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * F11.java
 *
 * Created on 15 Aug, 2017, 7:42:17 PM
 */

package Bank;

import java.sql.*;



import java.sql.Statement;

/**
 *
 * @author iayushag
 */
public class F11 extends javax.swing.JFrame {

    /** Creates new form F11 */
    public F11() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        op1 = new javax.swing.JOptionPane();
        buttonGroup1 = new javax.swing.ButtonGroup();
        label2 = new java.awt.Label();
        jLabel1 = new javax.swing.JLabel();
        acn = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        nr = new javax.swing.JRadioButton();
        ar = new javax.swing.JRadioButton();
        brh = new javax.swing.JRadioButton();
        nt = new javax.swing.JTextField();
        at = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        back = new javax.swing.JButton();
        label1 = new java.awt.Label();
        jButton6 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        c1 = new javax.swing.JComboBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        label2.setFont(new java.awt.Font("Comic Sans MS", 0, 16));
        label2.setForeground(new java.awt.Color(0, 153, 0));
        label2.setText("UPDATE DETAILS OF A ACCOUNT HOLDER");

        jLabel1.setFont(new java.awt.Font("Comic Sans MS", 1, 16));
        jLabel1.setForeground(new java.awt.Color(0, 153, 51));
        jLabel1.setText("Enter A/C num");

        jLabel2.setFont(new java.awt.Font("Comic Sans MS", 1, 16));
        jLabel2.setForeground(new java.awt.Color(0, 153, 51));
        jLabel2.setText("UPDATE:-");

        buttonGroup1.add(nr);
        nr.setFont(new java.awt.Font("Comic Sans MS", 1, 16)); // NOI18N
        nr.setForeground(new java.awt.Color(102, 51, 255));
        nr.setText("Name");
        nr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nrActionPerformed(evt);
            }
        });

        buttonGroup1.add(ar);
        ar.setFont(new java.awt.Font("Comic Sans MS", 1, 16)); // NOI18N
        ar.setForeground(new java.awt.Color(51, 51, 255));
        ar.setText("Address");
        ar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                arActionPerformed(evt);
            }
        });

        buttonGroup1.add(brh);
        brh.setFont(new java.awt.Font("Comic Sans MS", 1, 16)); // NOI18N
        brh.setForeground(new java.awt.Color(51, 51, 255));
        brh.setText("Branch");
        brh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                brhActionPerformed(evt);
            }
        });

        jButton1.setFont(new java.awt.Font("Comic Sans MS", 1, 20));
        jButton1.setForeground(new java.awt.Color(51, 102, 0));
        jButton1.setText("UPDATE DETAILS");
        jButton1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        back.setBackground(new java.awt.Color(102, 153, 255));
        back.setFont(new java.awt.Font("Tahoma", 1, 22));
        back.setForeground(new java.awt.Color(102, 102, 0));
        back.setText("<---");
        back.setBorder(null);
        back.setFocusCycleRoot(true);
        back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backActionPerformed(evt);
            }
        });

        label1.setFont(new java.awt.Font("Century Schoolbook", 1, 60));
        label1.setForeground(new java.awt.Color(51, 51, 255));
        label1.setText("Bank Of India");

        jButton6.setBackground(new java.awt.Color(204, 255, 255));
        jButton6.setFont(new java.awt.Font("Californian FB", 1, 14));
        jButton6.setText("Sign Out");
        jButton6.setBorder(null);
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        jButton9.setBackground(new java.awt.Color(153, 153, 255));
        jButton9.setFont(new java.awt.Font("Tahoma", 1, 22));
        jButton9.setText("X");
        jButton9.setBorder(new javax.swing.border.MatteBorder(null));
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });

        c1.setForeground(new java.awt.Color(51, 51, 255));
        c1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "vaishali_nagar", "bhankrota", "vidhyadhar_nagar", "chitrakut", "jagatpura", "tonk road" }));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(back, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(34, 34, 34))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap(101, Short.MAX_VALUE)
                        .addComponent(label1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(61, 61, 61)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButton9, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton6)))
            .addGroup(layout.createSequentialGroup()
                .addGap(136, 136, 136)
                .addComponent(label2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(169, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(36, 36, 36)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(nr)
                            .addComponent(nt, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(74, 74, 74)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(ar)
                            .addComponent(acn, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(55, 55, 55)
                        .addComponent(at, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(52, 52, 52)
                        .addComponent(c1, 0, 0, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(brh)
                        .addGap(62, 62, 62))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(229, Short.MAX_VALUE)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(220, 220, 220))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addComponent(label1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(label2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(acn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(19, 19, 19))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(18, 18, 18))))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton9, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(back, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nr)
                    .addComponent(ar)
                    .addComponent(jLabel2)
                    .addComponent(brh))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(at, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(c1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(48, 48, 48)
                .addComponent(jButton1)
                .addContainerGap(15, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    @SuppressWarnings("static-access")
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        String acno=acn.getText();
        String br="";
                 if(c1.getSelectedIndex()==0){
                 br=(String) c1.getSelectedItem();
                  }
                  if(c1.getSelectedIndex()==1){
                 br=(String) c1.getSelectedItem();
                  }
                  if(c1.getSelectedIndex()==2){
                 br=(String) c1.getSelectedItem();
                  }if(c1.getSelectedIndex()==3){
                 br=(String) c1.getSelectedItem();
                  }
                  if(c1.getSelectedIndex()==4){
                 br=(String) c1.getSelectedItem();
                  }
                  if(c1.getSelectedIndex()==5){
                 br=(String) c1.getSelectedItem();
                    }
         try{
                 Class.forName("java.sql.DriverManager");
                 Connection con = (Connection) DriverManager.getConnection("jdbc:mysql://localhost:3306/bankofind","root","root");
                 Statement stmt= (Statement) con.createStatement();
                 if(nr.isSelected()){
                                   String name=nt.getText();
                                   String query="update Bankdata SET Name='"+name+"' where Acc_no='"+acno+"';";
                                   stmt.executeUpdate(query);
                                   String query1="update Bankdataac SET Name='"+name+"' where Acc_no='"+acno+"';";
                                   stmt.executeUpdate(query1);
                                   op1.showMessageDialog(this,"Name Updated");
                                    }
                 else if(ar.isSelected()){
                                   String add=at.getText();
                                   String query="update Bankdata SET Address='"+add+"' where Acc_no='"+acno+"';";
                                   stmt.executeUpdate(query);
                                    op1.showMessageDialog(this,"Address Updated");
                                        }
                 else  if(brh.isSelected()){
                             String query="update Bankdata SET Branch='"+br+"' where Acc_no='"+acno+"';";
                                   stmt.executeUpdate(query);
                                    op1.showMessageDialog(this,"Branch updated");
                                    }
            }
                 catch(Exception e)
                    {
                   op1.showMessageDialog(this,e.getMessage());
                     }
                at.setText("");
                nt.setText("");
                acn.setText("");
    }//GEN-LAST:event_jButton1ActionPerformed

    private void nrActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nrActionPerformed
        // TODO add your handling code here:
        nt.setVisible(true);
        at.setVisible(false);
        c1.setVisible(false);
        
    }//GEN-LAST:event_nrActionPerformed

    private void arActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_arActionPerformed
        // TODO add your handling code here:
         at.setVisible(true);
        c1.setVisible(false);
        nt.setVisible(false);
    }//GEN-LAST:event_arActionPerformed

    private void brhActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_brhActionPerformed
        // TODO add your handling code here:
         c1.setVisible(true);
         at.setVisible(false);
         nt.setVisible(false);
}//GEN-LAST:event_brhActionPerformed

    private void backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backActionPerformed
        // TODO add your handling code here:
        F4 r= new F4();
        r.setVisible(true);
        this.dispose();
}//GEN-LAST:event_backActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
        F1_Login f=new F1_Login();
        f.setVisible(true);
        this.dispose();
}//GEN-LAST:event_jButton6ActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        // TODO add your handling code here:
        System.exit(0);
}//GEN-LAST:event_jButton9ActionPerformed

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new F11().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField acn;
    private javax.swing.JRadioButton ar;
    private javax.swing.JTextField at;
    private javax.swing.JButton back;
    private javax.swing.JRadioButton brh;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JComboBox c1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private java.awt.Label label1;
    private java.awt.Label label2;
    private javax.swing.JRadioButton nr;
    private javax.swing.JTextField nt;
    private javax.swing.JOptionPane op1;
    // End of variables declaration//GEN-END:variables

}
