/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * F8.java
 *
 * Created on 15 Aug, 2017, 2:05:38 PM
 */

package Bank;
import java.sql.*;

import java.sql.DriverManager;
import java.sql.ResultSet;

/**
 *
 * @author iayushag
 */
public class F8 extends javax.swing.JFrame {

    /** Creates new form F8 */
    public F8() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        op1 = new javax.swing.JOptionPane();
        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        nm = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        label2 = new java.awt.Label();
        jButton1 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        a1 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        da = new javax.swing.JTextField();
        de = new javax.swing.JRadioButton();
        wi = new javax.swing.JRadioButton();
        a2 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        cu = new javax.swing.JRadioButton();
        sa = new javax.swing.JRadioButton();
        jLabel7 = new javax.swing.JLabel();
        c1 = new javax.swing.JComboBox();
        jScrollPane1 = new javax.swing.JScrollPane();
        acn = new javax.swing.JTextArea();
        back = new javax.swing.JButton();
        label1 = new java.awt.Label();
        jButton6 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();

        op1.setBackground(new java.awt.Color(255, 102, 0));

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Comic Sans MS", 1, 14));
        jLabel1.setForeground(new java.awt.Color(0, 153, 0));
        jLabel1.setText("Enter Name");

        nm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nmActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Comic Sans MS", 1, 14));
        jLabel2.setForeground(new java.awt.Color(51, 153, 0));
        jLabel2.setText("Enter A/c Num");

        label2.setFont(new java.awt.Font("Comic Sans MS", 0, 16));
        label2.setForeground(new java.awt.Color(102, 153, 0));
        label2.setText("UPDATE TRANSACTION OF  ACCOUNT");

        jButton1.setFont(new java.awt.Font("Comic Sans MS", 1, 20));
        jButton1.setForeground(new java.awt.Color(102, 102, 0));
        jButton1.setText("UPDATE");
        jButton1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Comic Sans MS", 1, 14));
        jLabel3.setForeground(new java.awt.Color(51, 153, 0));
        jLabel3.setText("Amount");

        jLabel4.setFont(new java.awt.Font("Comic Sans MS", 1, 14));
        jLabel4.setForeground(new java.awt.Color(0, 153, 0));
        jLabel4.setText("Enter deposited date(yyyy-mm-dd)");

        buttonGroup1.add(de);
        de.setFont(new java.awt.Font("Comic Sans MS", 0, 14));
        de.setForeground(new java.awt.Color(153, 0, 204));
        de.setText("Deposit");
        de.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deActionPerformed(evt);
            }
        });

        buttonGroup1.add(wi);
        wi.setFont(new java.awt.Font("Comic Sans MS", 0, 14));
        wi.setForeground(new java.awt.Color(102, 51, 255));
        wi.setText("Withdraw");
        wi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                wiActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Comic Sans MS", 1, 14));
        jLabel5.setForeground(new java.awt.Color(0, 153, 0));
        jLabel5.setText("Enter Amount");

        jLabel6.setFont(new java.awt.Font("Comic Sans MS", 1, 14));
        jLabel6.setForeground(new java.awt.Color(51, 153, 0));
        jLabel6.setText("Account");

        buttonGroup2.add(cu);
        cu.setFont(new java.awt.Font("Comic Sans MS", 0, 14));
        cu.setForeground(new java.awt.Color(102, 51, 255));
        cu.setText("Current");

        buttonGroup2.add(sa);
        sa.setFont(new java.awt.Font("Comic Sans MS", 0, 14));
        sa.setForeground(new java.awt.Color(153, 0, 255));
        sa.setText("Saving");

        jLabel7.setFont(new java.awt.Font("Comic Sans MS", 1, 14));
        jLabel7.setForeground(new java.awt.Color(0, 153, 0));
        jLabel7.setText("Select Branch");

        c1.setFont(new java.awt.Font("Comic Sans MS", 0, 14));
        c1.setForeground(new java.awt.Color(51, 51, 255));
        c1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "vaishali nagar", "bhankrota", "vidhyadhar nagar", "chitrakut", "jagatpura", "tonk road" }));

        jScrollPane1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane1.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);

        acn.setColumns(20);
        acn.setRows(5);
        jScrollPane1.setViewportView(acn);

        back.setBackground(new java.awt.Color(102, 153, 255));
        back.setFont(new java.awt.Font("Tahoma", 1, 22));
        back.setForeground(new java.awt.Color(102, 102, 0));
        back.setText("<---");
        back.setBorder(null);
        back.setFocusCycleRoot(true);
        back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backActionPerformed(evt);
            }
        });

        label1.setFont(new java.awt.Font("Century Schoolbook", 1, 60));
        label1.setForeground(new java.awt.Color(51, 51, 255));
        label1.setText("Bank Of India");

        jButton6.setBackground(new java.awt.Color(204, 255, 255));
        jButton6.setFont(new java.awt.Font("Californian FB", 1, 14));
        jButton6.setText("Sign Out");
        jButton6.setBorder(null);
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        jButton9.setBackground(new java.awt.Color(153, 153, 255));
        jButton9.setFont(new java.awt.Font("Tahoma", 1, 22));
        jButton9.setText("X");
        jButton9.setBorder(new javax.swing.border.MatteBorder(null));
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(185, 185, 185)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addGap(67, 67, 67)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(a1, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(cu)))
                            .addComponent(jLabel5)
                            .addComponent(jLabel4))
                        .addGap(28, 28, 28)
                        .addComponent(da, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(de, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(18, 18, 18)
                                .addComponent(wi)
                                .addGap(143, 143, 143))
                            .addComponent(nm, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGap(104, 104, 104)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(sa)
                                    .addComponent(a2, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(154, 154, 154))))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addGap(47, 47, 47)
                        .addComponent(c1, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(310, 310, 310)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(233, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(153, 153, 153)
                .addComponent(label2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(169, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(back, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(114, 114, 114)
                        .addComponent(label1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 33, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButton6)
                    .addComponent(jButton9, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(back, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(2, 2, 2)
                        .addComponent(label1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(label2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(nm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel2)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(11, 11, 11)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(de)
                            .addComponent(wi))
                        .addGap(4, 4, 4)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(a1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(a2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(10, 10, 10)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(cu)
                            .addComponent(sa))
                        .addGap(8, 8, 8)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(c1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(32, 32, 32)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(da, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(29, 29, 29)
                        .addComponent(jButton1))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton9, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(2, 2, 2)
                        .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(31, 31, 31))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    @SuppressWarnings("static-access")
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
      String amo="0";
      String amo1="0";
       String name=nm.getText();
       String acno=acn.getText();
       String date=da.getText();
       if(name.isEmpty()){
           op1.showMessageDialog(null,"Name not Entered");
                         }
       if(date.isEmpty()){
           op1.showMessageDialog(null,"Date is not Entered");
                          }
        if(acno.isEmpty()){
           op1.showMessageDialog(null,"Account num is not Entered");
                          }
       String br="";
                 if(c1.getSelectedIndex()==0){
                 br=(String) c1.getSelectedItem();
                  }
                  if(c1.getSelectedIndex()==1){
                 br=(String) c1.getSelectedItem();
                  }
                  if(c1.getSelectedIndex()==2){
                 br=(String) c1.getSelectedItem();
                  }if(c1.getSelectedIndex()==3){
                 br=(String) c1.getSelectedItem();
                  }
                  if(c1.getSelectedIndex()==4){
                 br=(String) c1.getSelectedItem();
                  }
                  if(c1.getSelectedIndex()==5){
                 br=(String) c1.getSelectedItem();
                    }
       int am=0,am1=0;
       if(de.isSelected()){
                       am=Integer.parseInt(a1.getText());
                       am1=0;
                        amo=a1.getText();
                            if(amo.isEmpty()){
                                 op1.showMessageDialog(null,"Amount not Entered");
                                             }
                          }
       if(wi.isSelected()){
                        am1=Integer.parseInt(a2.getText());
                        am=0;
                         amo1=a2.getText();
                             if(amo1.isEmpty()){
                                 op1.showMessageDialog(null,"Amount not Entered");
                                     }
                               }
        try{
               Class.forName("java.sql.DriverManager");
               Connection con = (Connection) DriverManager.getConnection("jdbc:mysql://localhost:3306/bankofind","root","root");
               Statement stmt= (Statement) con.createStatement();
               String query="Select SavingsA_C,CurrentA_C from Bankdata where Name='"+name+"'and Acc_no='"+acno+"';";
               ResultSet rs=stmt.executeQuery(query);
              if(rs.next()){
                            String SavingA_C=rs.getString("SavingsA_C");
                            String CurrentA_C=rs.getString("CurrentA_C");
                           try{
                             Class.forName("java.sql.DriverManager");
                             Connection con3 = (Connection) DriverManager.getConnection("jdbc:mysql://localhost:3306/bankofind","root","root");
                             Statement stmt3= (Statement) con3.createStatement();
                              if(sa.isSelected()&&de.isSelected()){
                                            String query3="update Bankdata SET SavingsA_C=SavingsA_C+'"+am+"' where Acc_no='"+acno+"';";
                                            op1.showMessageDialog(this,"Amount deposited in Savings Account");
                                            stmt3.executeUpdate(query3);
                                                          }
                              else if(sa.isSelected()&&wi.isSelected()){
                                             String  query3="update Bankdata SET SavingsA_C=SavingsA_C-'"+am+"' where Acc_no='"+acno+"';";
                                             op1.showMessageDialog(this,"Amount withdral from Savings Account");
                                             stmt3.executeUpdate(query3);
                                                          }
                               else if(cu.isSelected()&&de.isSelected()){
                                            String query3="update Bankdata SET CurrentA_C=CurrentA_C+'"+am+"' where Acc_no='"+acno+"';";
                                            op1.showMessageDialog(this,"Amount deposited in Current Account");
                                            stmt3.executeUpdate(query3);
                                                          }
                                else if(cu.isSelected()&&wi.isSelected()){
                                            String query3="update Bankdata SET CurrentA_C=CurrentA_C-'"+am+"' where Acc_no='"+acno+"';";
                                            op1.showMessageDialog(this,"Amount withdral from Current Account");
                                            stmt3.executeUpdate(query3);
                                                          }

                             }
             catch(Exception e)
                    {
                   op1.showMessageDialog(this,e.getMessage());
                     }

             try{
                 Class.forName("java.sql.DriverManager");
                 Connection con1 = (Connection) DriverManager.getConnection("jdbc:mysql://localhost:3306/bankofind","root","root");
                 Statement stmt1= (Statement) con1.createStatement();
                 String query1="Insert into bankdataac values('"+acno+"','"+name+"','"+amo+"','"+date+"','"+br+"','"+amo1+"','"+date+"','"+br+"');";
                 stmt1.executeUpdate(query1);
                 nm.setText("");
                 acn.setText("");
                 da.setText("");
                 a1.setText("");
                 a2.setText("");
                }
              catch(Exception e)
                    {
                   op1.showMessageDialog(this,e.getMessage());
                     }
                           }
              else{
                            op1.showMessageDialog(null,"NO SUCH A/C OR NAME ");
                  }
              }

            catch(Exception e)
                    {
                   op1.showMessageDialog(this,e.getMessage());
                      }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void nmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nmActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nmActionPerformed

    private void deActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deActionPerformed
        // TODO add your handling code here:
        a2.setVisible(false);
        a1.setVisible(true);
    }//GEN-LAST:event_deActionPerformed

    private void wiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_wiActionPerformed
        // TODO add your handling code here:
        a1.setVisible(false);
        a2.setVisible(true);
    }//GEN-LAST:event_wiActionPerformed

    private void backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backActionPerformed
        // TODO add your handling code here:
        F4 r= new F4();
        r.setVisible(true);
        this.dispose();
}//GEN-LAST:event_backActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
        F1_Login f=new F1_Login();
        f.setVisible(true);
        this.dispose();
}//GEN-LAST:event_jButton6ActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        // TODO add your handling code here:
        System.exit(0);
}//GEN-LAST:event_jButton9ActionPerformed

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new F8().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField a1;
    private javax.swing.JTextField a2;
    private javax.swing.JTextArea acn;
    private javax.swing.JButton back;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JComboBox c1;
    private javax.swing.JRadioButton cu;
    private javax.swing.JTextField da;
    private javax.swing.JRadioButton de;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private java.awt.Label label1;
    private java.awt.Label label2;
    private javax.swing.JTextField nm;
    private javax.swing.JOptionPane op1;
    private javax.swing.JRadioButton sa;
    private javax.swing.JRadioButton wi;
    // End of variables declaration//GEN-END:variables

}
